<?php

use Illuminate\Database\Seeder;

class ComunasTableSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::table('comunas')->insert([
            ['cutProvincia'=>151, 'cutComuna'=>15101, 'nombre'=>'Arica'],
            ['cutProvincia'=>151, 'cutComuna'=>15102, 'nombre'=>'Camarones'],
            ['cutProvincia'=>152, 'cutComuna'=>15201, 'nombre'=>'Putre'],
            ['cutProvincia'=>152, 'cutComuna'=>15202, 'nombre'=>'General Lagos'],
            ['cutProvincia'=> 11, 'cutComuna'=> 1101, 'nombre'=>'Iquique'],
            ['cutProvincia'=> 11, 'cutComuna'=> 1107, 'nombre'=>'Alto Hospicio'],
            ['cutProvincia'=> 14, 'cutComuna'=> 1401, 'nombre'=>'Pozo Almonte'],
            ['cutProvincia'=> 14, 'cutComuna'=> 1402, 'nombre'=>'Camiña'],
            ['cutProvincia'=> 14, 'cutComuna'=> 1403, 'nombre'=>'Colchane'],
            ['cutProvincia'=> 14, 'cutComuna'=> 1404, 'nombre'=>'Huara'],
            ['cutProvincia'=> 14, 'cutComuna'=> 1405, 'nombre'=>'Pica'],
            ['cutProvincia'=> 21, 'cutComuna'=> 2101, 'nombre'=>'Antofagasta'],
            ['cutProvincia'=> 21, 'cutComuna'=> 2102, 'nombre'=>'Mejillones'],
            ['cutProvincia'=> 21, 'cutComuna'=> 2103, 'nombre'=>'Sierra Gorda'],
            ['cutProvincia'=> 21, 'cutComuna'=> 2104, 'nombre'=>'Taltal'],
            ['cutProvincia'=> 22, 'cutComuna'=> 2201, 'nombre'=>'Calama'],
            ['cutProvincia'=> 22, 'cutComuna'=> 2202, 'nombre'=>'Ollagüe'],
            ['cutProvincia'=> 22, 'cutComuna'=> 2203, 'nombre'=>'San Pedro de Atacama'],
            ['cutProvincia'=> 23, 'cutComuna'=> 2301, 'nombre'=>'Tocopilla'],
            ['cutProvincia'=> 23, 'cutComuna'=> 2302, 'nombre'=>'María Elena'],
            ['cutProvincia'=> 31, 'cutComuna'=> 3101, 'nombre'=>'Copiapó'],
            ['cutProvincia'=> 31, 'cutComuna'=> 3102, 'nombre'=>'Caldera'],
            ['cutProvincia'=> 31, 'cutComuna'=> 3103, 'nombre'=>'Tierra Amarilla'],
            ['cutProvincia'=> 32, 'cutComuna'=> 3201, 'nombre'=>'Chañaral'],
            ['cutProvincia'=> 32, 'cutComuna'=> 3202, 'nombre'=>'Diego de Almagro'],
            ['cutProvincia'=> 33, 'cutComuna'=> 3301, 'nombre'=>'Vallenar'],
            ['cutProvincia'=> 33, 'cutComuna'=> 3302, 'nombre'=>'Alto del Carmen'],
            ['cutProvincia'=> 33, 'cutComuna'=> 3303, 'nombre'=>'Freirina'],
            ['cutProvincia'=> 33, 'cutComuna'=> 3304, 'nombre'=>'Huasco'],
            ['cutProvincia'=> 41, 'cutComuna'=> 4101, 'nombre'=>'La Serena'],
            ['cutProvincia'=> 41, 'cutComuna'=> 4102, 'nombre'=>'Coquimbo'],
            ['cutProvincia'=> 41, 'cutComuna'=> 4103, 'nombre'=>'Andacollo'],
            ['cutProvincia'=> 41, 'cutComuna'=> 4104, 'nombre'=>'La Higuera'],
            ['cutProvincia'=> 41, 'cutComuna'=> 4105, 'nombre'=>'Paiguano'],
            ['cutProvincia'=> 41, 'cutComuna'=> 4106, 'nombre'=>'Vicuña'],
            ['cutProvincia'=> 42, 'cutComuna'=> 4201, 'nombre'=>'Illapel'],
            ['cutProvincia'=> 42, 'cutComuna'=> 4202, 'nombre'=>'Canela'],
            ['cutProvincia'=> 42, 'cutComuna'=> 4203, 'nombre'=>'Los Vilos'],
            ['cutProvincia'=> 42, 'cutComuna'=> 4204, 'nombre'=>'Salamanca'],
            ['cutProvincia'=> 43, 'cutComuna'=> 4301, 'nombre'=>'Ovalle'],
            ['cutProvincia'=> 43, 'cutComuna'=> 4302, 'nombre'=>'Combarbalá'],
            ['cutProvincia'=> 43, 'cutComuna'=> 4303, 'nombre'=>'Monte Patria'],
            ['cutProvincia'=> 43, 'cutComuna'=> 4304, 'nombre'=>'Punitaqui'],
            ['cutProvincia'=> 43, 'cutComuna'=> 4305, 'nombre'=>'Río Hurtado'],
            ['cutProvincia'=> 51, 'cutComuna'=> 5101, 'nombre'=>'Valparaíso'],
            ['cutProvincia'=> 51, 'cutComuna'=> 5102, 'nombre'=>'Casablanca'],
            ['cutProvincia'=> 51, 'cutComuna'=> 5103, 'nombre'=>'Concón'],
            ['cutProvincia'=> 51, 'cutComuna'=> 5104, 'nombre'=>'Juan Fernández'],
            ['cutProvincia'=> 51, 'cutComuna'=> 5105, 'nombre'=>'Puchuncaví'],
            ['cutProvincia'=> 51, 'cutComuna'=> 5107, 'nombre'=>'Quintero'],
            ['cutProvincia'=> 51, 'cutComuna'=> 5109, 'nombre'=>'Viña del Mar'],
            ['cutProvincia'=> 52, 'cutComuna'=> 5201, 'nombre'=>'Isla de Pascua'],
            ['cutProvincia'=> 53, 'cutComuna'=> 5301, 'nombre'=>'Los Andes'],
            ['cutProvincia'=> 53, 'cutComuna'=> 5302, 'nombre'=>'Calle Larga'],
            ['cutProvincia'=> 53, 'cutComuna'=> 5303, 'nombre'=>'Rinconada'],
            ['cutProvincia'=> 53, 'cutComuna'=> 5304, 'nombre'=>'San Esteban'],
            ['cutProvincia'=> 54, 'cutComuna'=> 5401, 'nombre'=>'La Ligua'],
            ['cutProvincia'=> 54, 'cutComuna'=> 5402, 'nombre'=>'Cabildo'],
            ['cutProvincia'=> 54, 'cutComuna'=> 5403, 'nombre'=>'Papudo'],
            ['cutProvincia'=> 54, 'cutComuna'=> 5404, 'nombre'=>'Petorca'],
            ['cutProvincia'=> 54, 'cutComuna'=> 5405, 'nombre'=>'Zapallar'],
            ['cutProvincia'=> 55, 'cutComuna'=> 5501, 'nombre'=>'Quillota'],
            ['cutProvincia'=> 55, 'cutComuna'=> 5502, 'nombre'=>'La Calera'],
            ['cutProvincia'=> 55, 'cutComuna'=> 5503, 'nombre'=>'Hijuelas'],
            ['cutProvincia'=> 55, 'cutComuna'=> 5504, 'nombre'=>'La Cruz'],
            ['cutProvincia'=> 55, 'cutComuna'=> 5506, 'nombre'=>'Nogales'],
            ['cutProvincia'=> 56, 'cutComuna'=> 5601, 'nombre'=>'San Antonio'],
            ['cutProvincia'=> 56, 'cutComuna'=> 5602, 'nombre'=>'Algarrobo'],
            ['cutProvincia'=> 56, 'cutComuna'=> 5603, 'nombre'=>'Cartagena'],
            ['cutProvincia'=> 56, 'cutComuna'=> 5604, 'nombre'=>'El Quisco'],
            ['cutProvincia'=> 56, 'cutComuna'=> 5605, 'nombre'=>'El Tabo'],
            ['cutProvincia'=> 56, 'cutComuna'=> 5606, 'nombre'=>'Santo Domingo'],
            ['cutProvincia'=> 57, 'cutComuna'=> 5701, 'nombre'=>'San Felipe'],
            ['cutProvincia'=> 57, 'cutComuna'=> 5702, 'nombre'=>'Catemu'],
            ['cutProvincia'=> 57, 'cutComuna'=> 5703, 'nombre'=>'Llaillay'],
            ['cutProvincia'=> 57, 'cutComuna'=> 5704, 'nombre'=>'Panquehue'],
            ['cutProvincia'=> 57, 'cutComuna'=> 5705, 'nombre'=>'Putaendo'],
            ['cutProvincia'=> 57, 'cutComuna'=> 5706, 'nombre'=>'Santa María'],
            ['cutProvincia'=> 58, 'cutComuna'=> 5801, 'nombre'=>'Quilpué'],
            ['cutProvincia'=> 58, 'cutComuna'=> 5802, 'nombre'=>'Limache'],
            ['cutProvincia'=> 58, 'cutComuna'=> 5803, 'nombre'=>'Olmué'],
            ['cutProvincia'=> 58, 'cutComuna'=> 5804, 'nombre'=>'Villa Alemana'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6101, 'nombre'=>'Rancagua'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6102, 'nombre'=>'Codegua'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6103, 'nombre'=>'Coinco'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6104, 'nombre'=>'Coltauco'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6105, 'nombre'=>'Doñihue'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6106, 'nombre'=>'Graneros'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6107, 'nombre'=>'Las Cabras'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6108, 'nombre'=>'Machalí'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6109, 'nombre'=>'Malloa'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6110, 'nombre'=>'Mostazal'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6111, 'nombre'=>'Olivar'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6112, 'nombre'=>'Peumo'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6113, 'nombre'=>'Pichidegua'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6114, 'nombre'=>'Quinta de Tilcoco'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6115, 'nombre'=>'Rengo'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6116, 'nombre'=>'Requínoa'],
            ['cutProvincia'=> 61, 'cutComuna'=> 6117, 'nombre'=>'San Vicente de Tagua Tagua'],
            ['cutProvincia'=> 62, 'cutComuna'=> 6201, 'nombre'=>'Pichilemu'],
            ['cutProvincia'=> 62, 'cutComuna'=> 6202, 'nombre'=>'La Estrella'],
            ['cutProvincia'=> 62, 'cutComuna'=> 6203, 'nombre'=>'Litueche'],
            ['cutProvincia'=> 62, 'cutComuna'=> 6204, 'nombre'=>'Marchihue'],
            ['cutProvincia'=> 62, 'cutComuna'=> 6205, 'nombre'=>'Navidad'],
            ['cutProvincia'=> 62, 'cutComuna'=> 6206, 'nombre'=>'Paredones'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6301, 'nombre'=>'San Fernando'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6302, 'nombre'=>'Chépica'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6303, 'nombre'=>'Chimbarongo'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6304, 'nombre'=>'Lolol'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6305, 'nombre'=>'Nancagua'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6306, 'nombre'=>'Palmilla'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6307, 'nombre'=>'Peralillo'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6308, 'nombre'=>'Placilla'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6309, 'nombre'=>'Pumanque'],
            ['cutProvincia'=> 63, 'cutComuna'=> 6310, 'nombre'=>'Santa Cruz'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7101, 'nombre'=>'Talca'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7102, 'nombre'=>'Constitución'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7103, 'nombre'=>'Curepto'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7104, 'nombre'=>'Empedrado'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7105, 'nombre'=>'Maule'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7106, 'nombre'=>'Pelarco'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7107, 'nombre'=>'Pencahue'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7108, 'nombre'=>'Río Claro'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7109, 'nombre'=>'San Clemente'],
            ['cutProvincia'=> 71, 'cutComuna'=> 7110, 'nombre'=>'San Rafael'],
            ['cutProvincia'=> 72, 'cutComuna'=> 7201, 'nombre'=>'Cauquenes'],
            ['cutProvincia'=> 72, 'cutComuna'=> 7202, 'nombre'=>'Chanco'],
            ['cutProvincia'=> 72, 'cutComuna'=> 7203, 'nombre'=>'Pelluhue'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7301, 'nombre'=>'Curicó'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7302, 'nombre'=>'Hualañé'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7303, 'nombre'=>'Licantén'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7304, 'nombre'=>'Molina'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7305, 'nombre'=>'Rauco'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7306, 'nombre'=>'Romeral'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7307, 'nombre'=>'Sagrada Familia'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7308, 'nombre'=>'Teno'],
            ['cutProvincia'=> 73, 'cutComuna'=> 7309, 'nombre'=>'Vichuquén'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7401, 'nombre'=>'Linares'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7402, 'nombre'=>'Colbún'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7403, 'nombre'=>'Longaví'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7404, 'nombre'=>'Parral'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7405, 'nombre'=>'Retiro'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7406, 'nombre'=>'San Javier'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7407, 'nombre'=>'Villa Alegre'],
            ['cutProvincia'=> 74, 'cutComuna'=> 7408, 'nombre'=>'Yerbas Buenas'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8101, 'nombre'=>'Concepción'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8102, 'nombre'=>'Coronel'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8103, 'nombre'=>'Chiguayante'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8104, 'nombre'=>'Florida'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8105, 'nombre'=>'Hualqui'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8106, 'nombre'=>'Lota'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8107, 'nombre'=>'Penco'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8108, 'nombre'=>'San Pedro de la Paz'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8109, 'nombre'=>'Santa Juana'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8110, 'nombre'=>'Talcahuano'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8111, 'nombre'=>'Tomé'],
            ['cutProvincia'=> 81, 'cutComuna'=> 8112, 'nombre'=>'Hualpén'],
            ['cutProvincia'=> 82, 'cutComuna'=> 8201, 'nombre'=>'Lebu'],
            ['cutProvincia'=> 82, 'cutComuna'=> 8202, 'nombre'=>'Arauco'],
            ['cutProvincia'=> 82, 'cutComuna'=> 8203, 'nombre'=>'Cañete'],
            ['cutProvincia'=> 82, 'cutComuna'=> 8204, 'nombre'=>'Contulmo'],
            ['cutProvincia'=> 82, 'cutComuna'=> 8205, 'nombre'=>'Curanilahue'],
            ['cutProvincia'=> 82, 'cutComuna'=> 8206, 'nombre'=>'Los Álamos'],
            ['cutProvincia'=> 82, 'cutComuna'=> 8207, 'nombre'=>'Tirúa'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8301, 'nombre'=>'Los Ángeles'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8302, 'nombre'=>'Antuco'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8303, 'nombre'=>'Cabrero'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8304, 'nombre'=>'Laja'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8305, 'nombre'=>'Mulchén'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8306, 'nombre'=>'Nacimiento'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8307, 'nombre'=>'Negrete'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8308, 'nombre'=>'Quilaco'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8309, 'nombre'=>'Quilleco'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8310, 'nombre'=>'San Rosendo'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8311, 'nombre'=>'Santa Bárbara'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8312, 'nombre'=>'Tucapel'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8313, 'nombre'=>'Yumbel'],
            ['cutProvincia'=> 83, 'cutComuna'=> 8314, 'nombre'=>'Alto Biobío'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8401, 'nombre'=>'Chillán'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8402, 'nombre'=>'Bulnes'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8403, 'nombre'=>'Cobquecura'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8404, 'nombre'=>'Coelemu'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8405, 'nombre'=>'Coihueco'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8406, 'nombre'=>'Chillán Viejo'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8407, 'nombre'=>'El Carmen'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8408, 'nombre'=>'Ninhue'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8409, 'nombre'=>'Ñiquén'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8410, 'nombre'=>'Pemuco'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8411, 'nombre'=>'Pinto'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8412, 'nombre'=>'Portezuelo'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8413, 'nombre'=>'Quillón'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8414, 'nombre'=>'Quirihue'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8415, 'nombre'=>'Ránquil'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8416, 'nombre'=>'San Carlos'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8417, 'nombre'=>'San Fabián'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8418, 'nombre'=>'San Ignacio'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8419, 'nombre'=>'San Nicolás'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8420, 'nombre'=>'Treguaco'],
            ['cutProvincia'=> 84, 'cutComuna'=> 8421, 'nombre'=>'Yungay'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9101, 'nombre'=>'Temuco'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9102, 'nombre'=>'Carahue'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9103, 'nombre'=>'Cunco'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9104, 'nombre'=>'Curarrehue'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9105, 'nombre'=>'Freire'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9106, 'nombre'=>'Galvarino'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9107, 'nombre'=>'Gorbea'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9108, 'nombre'=>'Lautaro'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9109, 'nombre'=>'Loncoche'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9110, 'nombre'=>'Melipeuco'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9111, 'nombre'=>'Nueva Imperial'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9112, 'nombre'=>'Padre Las Casas'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9113, 'nombre'=>'Perquenco'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9114, 'nombre'=>'Pitrufquén'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9115, 'nombre'=>'Pucón'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9116, 'nombre'=>'Saavedra'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9117, 'nombre'=>'Teodoro Schmidt'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9118, 'nombre'=>'Toltén'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9119, 'nombre'=>'Vilcún'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9120, 'nombre'=>'Villarrica'],
            ['cutProvincia'=> 91, 'cutComuna'=> 9121, 'nombre'=>'Cholchol'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9201, 'nombre'=>'Angol'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9202, 'nombre'=>'Collipulli'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9203, 'nombre'=>'Curacautín'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9204, 'nombre'=>'Ercilla'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9205, 'nombre'=>'Lonquimay'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9206, 'nombre'=>'Los Sauces'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9207, 'nombre'=>'Lumaco'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9208, 'nombre'=>'Purén'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9209, 'nombre'=>'Renaico'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9210, 'nombre'=>'Traiguén'],
            ['cutProvincia'=> 92, 'cutComuna'=> 9211, 'nombre'=>'Victoria'],
            ['cutProvincia'=>141, 'cutComuna'=>14101, 'nombre'=>'Valdivia'],
            ['cutProvincia'=>141, 'cutComuna'=>14102, 'nombre'=>'Corral'],
            ['cutProvincia'=>141, 'cutComuna'=>14103, 'nombre'=>'Lanco'],
            ['cutProvincia'=>141, 'cutComuna'=>14104, 'nombre'=>'Los Lagos'],
            ['cutProvincia'=>141, 'cutComuna'=>14105, 'nombre'=>'Máfil'],
            ['cutProvincia'=>141, 'cutComuna'=>14106, 'nombre'=>'Mariquina'],
            ['cutProvincia'=>141, 'cutComuna'=>14107, 'nombre'=>'Paillaco'],
            ['cutProvincia'=>141, 'cutComuna'=>14108, 'nombre'=>'Panguipulli'],
            ['cutProvincia'=>142, 'cutComuna'=>14201, 'nombre'=>'La Unión'],
            ['cutProvincia'=>142, 'cutComuna'=>14202, 'nombre'=>'Futrono'],
            ['cutProvincia'=>142, 'cutComuna'=>14203, 'nombre'=>'Lago Ranco'],
            ['cutProvincia'=>142, 'cutComuna'=>14204, 'nombre'=>'Río Bueno'],
            ['cutProvincia'=>101, 'cutComuna'=>10101, 'nombre'=>'Puerto Montt'],
            ['cutProvincia'=>101, 'cutComuna'=>10102, 'nombre'=>'Calbuco'],
            ['cutProvincia'=>101, 'cutComuna'=>10103, 'nombre'=>'Cochamó'],
            ['cutProvincia'=>101, 'cutComuna'=>10104, 'nombre'=>'Fresia'],
            ['cutProvincia'=>101, 'cutComuna'=>10105, 'nombre'=>'Frutillar'],
            ['cutProvincia'=>101, 'cutComuna'=>10106, 'nombre'=>'Los Muermos'],
            ['cutProvincia'=>101, 'cutComuna'=>10107, 'nombre'=>'Llanquihue'],
            ['cutProvincia'=>101, 'cutComuna'=>10108, 'nombre'=>'Maullín'],
            ['cutProvincia'=>101, 'cutComuna'=>10109, 'nombre'=>'Puerto Varas'],
            ['cutProvincia'=>102, 'cutComuna'=>10201, 'nombre'=>'Castro'],
            ['cutProvincia'=>102, 'cutComuna'=>10202, 'nombre'=>'Ancud'],
            ['cutProvincia'=>102, 'cutComuna'=>10203, 'nombre'=>'Chonchi'],
            ['cutProvincia'=>102, 'cutComuna'=>10204, 'nombre'=>'Curaco de Vélez'],
            ['cutProvincia'=>102, 'cutComuna'=>10205, 'nombre'=>'Dalcahue'],
            ['cutProvincia'=>102, 'cutComuna'=>10206, 'nombre'=>'Puqueldón'],
            ['cutProvincia'=>102, 'cutComuna'=>10207, 'nombre'=>'Queilén'],
            ['cutProvincia'=>102, 'cutComuna'=>10208, 'nombre'=>'Quellón'],
            ['cutProvincia'=>102, 'cutComuna'=>10209, 'nombre'=>'Quemchi'],
            ['cutProvincia'=>102, 'cutComuna'=>10210, 'nombre'=>'Quinchao'],
            ['cutProvincia'=>103, 'cutComuna'=>10301, 'nombre'=>'Osorno'],
            ['cutProvincia'=>103, 'cutComuna'=>10302, 'nombre'=>'Puerto Octay'],
            ['cutProvincia'=>103, 'cutComuna'=>10303, 'nombre'=>'Purranque'],
            ['cutProvincia'=>103, 'cutComuna'=>10304, 'nombre'=>'Puyehue'],
            ['cutProvincia'=>103, 'cutComuna'=>10305, 'nombre'=>'Río Negro'],
            ['cutProvincia'=>103, 'cutComuna'=>10306, 'nombre'=>'San Juan de la Costa'],
            ['cutProvincia'=>103, 'cutComuna'=>10307, 'nombre'=>'San Pablo'],
            ['cutProvincia'=>104, 'cutComuna'=>10401, 'nombre'=>'Chaitén'],
            ['cutProvincia'=>104, 'cutComuna'=>10402, 'nombre'=>'Futaleufú'],
            ['cutProvincia'=>104, 'cutComuna'=>10403, 'nombre'=>'Hualaihué'],
            ['cutProvincia'=>104, 'cutComuna'=>10404, 'nombre'=>'Palena'],
            ['cutProvincia'=>111, 'cutComuna'=>11101, 'nombre'=>'Coyhaique'],
            ['cutProvincia'=>111, 'cutComuna'=>11102, 'nombre'=>'Lago Verde'],
            ['cutProvincia'=>112, 'cutComuna'=>11201, 'nombre'=>'Aysén'],
            ['cutProvincia'=>112, 'cutComuna'=>11202, 'nombre'=>'Cisnes'],
            ['cutProvincia'=>112, 'cutComuna'=>11203, 'nombre'=>'Guaitecas'],
            ['cutProvincia'=>113, 'cutComuna'=>11301, 'nombre'=>'Cochrane'],
            ['cutProvincia'=>113, 'cutComuna'=>11302, 'nombre'=>'O’Higgins'],
            ['cutProvincia'=>113, 'cutComuna'=>11303, 'nombre'=>'Tortel'],
            ['cutProvincia'=>114, 'cutComuna'=>11401, 'nombre'=>'Chile Chico'],
            ['cutProvincia'=>114, 'cutComuna'=>11402, 'nombre'=>'Río Ibáñez'],
            ['cutProvincia'=>121, 'cutComuna'=>12101, 'nombre'=>'Punta Arenas'],
            ['cutProvincia'=>121, 'cutComuna'=>12102, 'nombre'=>'Laguna Blanca'],
            ['cutProvincia'=>121, 'cutComuna'=>12103, 'nombre'=>'Río Verde'],
            ['cutProvincia'=>121, 'cutComuna'=>12104, 'nombre'=>'San Gregorio'],
            ['cutProvincia'=>122, 'cutComuna'=>12201, 'nombre'=>'Cabo de Hornos (Ex - Navarino)'],
            ['cutProvincia'=>122, 'cutComuna'=>12202, 'nombre'=>'Antártica'],
            ['cutProvincia'=>123, 'cutComuna'=>12301, 'nombre'=>'Porvenir'],
            ['cutProvincia'=>123, 'cutComuna'=>12302, 'nombre'=>'Primavera'],
            ['cutProvincia'=>123, 'cutComuna'=>12303, 'nombre'=>'Timaukel'],
            ['cutProvincia'=>124, 'cutComuna'=>12401, 'nombre'=>'Natales'],
            ['cutProvincia'=>124, 'cutComuna'=>12402, 'nombre'=>'Torres del Paine'],
            ['cutProvincia'=>131, 'cutComuna'=>13101, 'nombre'=>'Santiago'],
            ['cutProvincia'=>131, 'cutComuna'=>13102, 'nombre'=>'Cerrillos'],
            ['cutProvincia'=>131, 'cutComuna'=>13103, 'nombre'=>'Cerro Navia'],
            ['cutProvincia'=>131, 'cutComuna'=>13104, 'nombre'=>'Conchalí'],
            ['cutProvincia'=>131, 'cutComuna'=>13105, 'nombre'=>'El Bosque'],
            ['cutProvincia'=>131, 'cutComuna'=>13106, 'nombre'=>'Estación Central'],
            ['cutProvincia'=>131, 'cutComuna'=>13107, 'nombre'=>'Huechuraba'],
            ['cutProvincia'=>131, 'cutComuna'=>13108, 'nombre'=>'Independencia'],
            ['cutProvincia'=>131, 'cutComuna'=>13109, 'nombre'=>'La Cisterna'],
            ['cutProvincia'=>131, 'cutComuna'=>13110, 'nombre'=>'La Florida'],
            ['cutProvincia'=>131, 'cutComuna'=>13111, 'nombre'=>'La Granja'],
            ['cutProvincia'=>131, 'cutComuna'=>13112, 'nombre'=>'La Pintana'],
            ['cutProvincia'=>131, 'cutComuna'=>13113, 'nombre'=>'La Reina'],
            ['cutProvincia'=>131, 'cutComuna'=>13114, 'nombre'=>'Las Condes'],
            ['cutProvincia'=>131, 'cutComuna'=>13115, 'nombre'=>'Lo Barnechea'],
            ['cutProvincia'=>131, 'cutComuna'=>13116, 'nombre'=>'Lo Espejo'],
            ['cutProvincia'=>131, 'cutComuna'=>13117, 'nombre'=>'Lo Prado'],
            ['cutProvincia'=>131, 'cutComuna'=>13118, 'nombre'=>'Macul'],
            ['cutProvincia'=>131, 'cutComuna'=>13119, 'nombre'=>'Maipú'],
            ['cutProvincia'=>131, 'cutComuna'=>13120, 'nombre'=>'Ñuñoa'],
            ['cutProvincia'=>131, 'cutComuna'=>13121, 'nombre'=>'Pedro Aguirre Cerda'],
            ['cutProvincia'=>131, 'cutComuna'=>13122, 'nombre'=>'Peñalolén'],
            ['cutProvincia'=>131, 'cutComuna'=>13123, 'nombre'=>'Providencia'],
            ['cutProvincia'=>131, 'cutComuna'=>13124, 'nombre'=>'Pudahuel'],
            ['cutProvincia'=>131, 'cutComuna'=>13125, 'nombre'=>'Quilicura'],
            ['cutProvincia'=>131, 'cutComuna'=>13126, 'nombre'=>'Quinta Normal'],
            ['cutProvincia'=>131, 'cutComuna'=>13127, 'nombre'=>'Recoleta'],
            ['cutProvincia'=>131, 'cutComuna'=>13128, 'nombre'=>'Renca'],
            ['cutProvincia'=>131, 'cutComuna'=>13129, 'nombre'=>'San Joaquín'],
            ['cutProvincia'=>131, 'cutComuna'=>13130, 'nombre'=>'San Miguel'],
            ['cutProvincia'=>131, 'cutComuna'=>13131, 'nombre'=>'San Ramón'],
            ['cutProvincia'=>131, 'cutComuna'=>13132, 'nombre'=>'Vitacura'],
            ['cutProvincia'=>132, 'cutComuna'=>13201, 'nombre'=>'Puente Alto'],
            ['cutProvincia'=>132, 'cutComuna'=>13202, 'nombre'=>'Pirque'],
            ['cutProvincia'=>132, 'cutComuna'=>13203, 'nombre'=>'San José de Maipo'],
            ['cutProvincia'=>133, 'cutComuna'=>13301, 'nombre'=>'Colina'],
            ['cutProvincia'=>133, 'cutComuna'=>13302, 'nombre'=>'Lampa '],
            ['cutProvincia'=>133, 'cutComuna'=>13303, 'nombre'=>'Tiltil'],
            ['cutProvincia'=>134, 'cutComuna'=>13401, 'nombre'=>'San Bernardo'],
            ['cutProvincia'=>134, 'cutComuna'=>13402, 'nombre'=>'Buin'],
            ['cutProvincia'=>134, 'cutComuna'=>13403, 'nombre'=>'Calera de Tango'],
            ['cutProvincia'=>134, 'cutComuna'=>13404, 'nombre'=>'Paine'],
            ['cutProvincia'=>135, 'cutComuna'=>13501, 'nombre'=>'Melipilla'],
            ['cutProvincia'=>135, 'cutComuna'=>13502, 'nombre'=>'Alhué'],
            ['cutProvincia'=>135, 'cutComuna'=>13503, 'nombre'=>'Curacaví'],
            ['cutProvincia'=>135, 'cutComuna'=>13504, 'nombre'=>'María Pinto'],
            ['cutProvincia'=>135, 'cutComuna'=>13505, 'nombre'=>'San Pedro'],
            ['cutProvincia'=>136, 'cutComuna'=>13601, 'nombre'=>'Talagante'],
            ['cutProvincia'=>136, 'cutComuna'=>13602, 'nombre'=>'El Monte'],
            ['cutProvincia'=>136, 'cutComuna'=>13603, 'nombre'=>'Isla de Maipo'],
            ['cutProvincia'=>136, 'cutComuna'=>13604, 'nombre'=>'Padre Hurtado'],
            ['cutProvincia'=>136, 'cutComuna'=>13605, 'nombre'=>'Peñaflor']
        ]);
    }
}
